name: sc-docker-standalone-bldr

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "**" ]
    paths:
      - '.github/workflows/sc-docker-standalone-bldr.yml'
      - 'dockerfiles/Dockerfile'
      - 'npu/broadcom/BCM56850/saivs/Dockerfile'
      - 'npu/broadcom/BCM56850/saivs/Dockerfile.saithrift'
      - 'common/'
      - 'builds/'
      - 'cli/'
      - 'scripts/'
      - 'configs/'
      - 'setup.py'
      - 'build.sh'
      - '.dockerignore'
  
jobs:   
  build-sc-stadalone-thrift:
    name: Build SAI Challenger standalone image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Update submodules
      run: git submodule update --init
    - name: Build standalone docker image
      run: ./build.sh -i standalone
    - name: Start SAI-C in standalone mode
      run: ./run.sh -i standalone
    - name: Wait for SAI-C services to come up
      run: sleep 10s
    - name: Run tests
      run: ./exec.sh --no-tty pytest --testbed=saivs_standalone -v -k "test_l2_basic"
    - name: Build standalone docker image with SAI thrift
      run: ./build.sh -i standalone -s thrift
